### ISSUE TITLE
Differences with `django-two-factor-auth`?

### ISSUE THREAD

**Issue by barseghyanartur** [kaleissin/django-verification#8]
What are the differences between this project and [django-two-factor-auth](https://github.com/Bouke/django-two-factor-auth)?

**Comment by kaleissin** [comment]
`django-verification` gives you a generated code and a link to do something with that code, and what you use it for is up to you. `django-two-factor-auth` seems to be for, well 2FA.

I've yet to use `django-verification` to build a 2FA-system for my own projects though it was originally funded for 2FA. I've used it for (physical) tickets at events and for invites to access non-public resources.

If you just want 2FA then go with whatever you find easiest to use.
